name: Setup AtomiCloud CI Docker
description: 'Setup AtomiCloud CI Docker (Compatible with Namespace)'
inputs:
  namespacelabs:
    default: 'true'
    description: "Using Namespace Lab's runners"
  checkout:
    default: 'native'
    description: |
      Whether to checkout the repository and what checkout action to use. Avaiable
      options are `false`, `native`, `namespace`
  short-length:
    default: 7
    description: length for short SHA values generated. See rlespinasse/github-slug-action.

branding:
  color: blue
  icon: settings
runs:
  using: 'composite'
  steps:
    # Checkout
    - name: Checkout Repository
      uses: namespacelabs/nscloud-checkout-action@v5
      if: inputs.checkout == 'namespace'
    - name: Checkout Repository
      uses: actions/checkout@v4
      if: inputs.checkout == 'native'

    # NAMESPACE LAB VERSION
    - name: Install and configure Namespace CLI
      uses: namespacelabs/nscloud-setup@v0
      if: inputs.namespacelabs == 'true'
    - name: Configure Namespace powered Buildx
      uses: namespacelabs/nscloud-setup-buildx-action@v0
      if: inputs.namespacelabs == 'true'

    # NATIVE VERSION
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v3
      if: inputs.namespacelabs == 'false'
    - name: Setup QEMU emulator
      uses: docker/setup-qemu-action@v3
      if: inputs.namespacelabs == 'false'

    - name: Inject enhanced GitHub environment variables
      uses: rlespinasse/github-slug-action@v5.x
      with:
        short-length: ${{ inputs.short-length }}
